# Generated by Django 2.0.5 on 2018-05-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_title',
            field=models.CharField(default='ghufgj', max_length=250),
        ),
    ]
